apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

patches:
  - path: ingress.patch.yaml
    target:
      kind: Ingress
      name: ingress-load-balancer
  - path: ingress.patch.json
    target:
      kind: Ingress
      name: ingress-load-balancer
