apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

images:
  - name: mycontainerregistry.azurecr.io/backend
    # IMAGE_TAG is substituted during GitLab build
    newTag: IMAGE_TAG
